spring:                 #打包配置
  profiles: 
    active:
      - dev

---
spring:    
  profiles: dev
  application:
    name: cloudServer-provider-faceServer
eureka:       #客户端连接注册的配置
  client:
    service-url:
    #单台注册可以多台传递，建议多台注册HA安全保证提高可靠性
      defaultZone: http://hcr:hcr12356@192.168.1.134:7001/eureka,http://hcr:hcr12356@192.168.1.134:7002/eureka
 
---
spring: 
  profiles: beta   
  application:
    name: cloudServer-provider-faceServer
eureka:       #客户端连接注册的配置
  client:
    service-url:
    #单台注册可以多台传递，建议多台注册HA安全保证提高可靠性
      defaultZone: http://hcr:hcr12356@192.168.1.134:7001/eureka,http://hcr:hcr12356@192.168.1.134:7002/eureka
 

   
  
      
      
