spring:                 #打包配置
  profiles: 
    active:
      - dev

---
server:
  port: 9001
spring:
  profiles: beta9001
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://192.168.1.52:3306/prisondcdb
      username: huangcongrui
      password: azyd123
      platform: mysql
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      #minEvictableIdleTimeMillis: 30000
      #validationQuery: select 1
      #testWhileIdle: true
      #testOnBorrow: false
      #testOnReturn: false
      
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
  application:
    name: cloudServer-provider-duty   #配置eureka服务上的挂载id名，该配置需要进入配置管理流程严格控制
    
eureka:       #客户端连接注册的配置
  client:
    service-url:
    #单台注册可以多台传递，建议多台注册HA安全保证提高可靠性
      defaultZone: http://hcr:hcr12356@192.168.1.134:7001/eureka,http://hcr:hcr12356@192.168.1.134:7002/eureka
  instance:
#    lease-renewal-interval-in-seconds: 2 #设置心跳间隔时间（默认30）
#    lease-expiration-duration-in-seconds: 5 #Server应该收到心跳数据的间隔周期（默认90秒）
    instance-id: 192.168.1.134:9001        #配置显示地址信息
    prefer-ip-address: true           #以真实地址显示服务ip信息

#info信息,进入配置管理，便于维护
info:
  app.name: cloudServer
  company.name: angeasy
  build.artifactId: $project.artifactId$
  build.version: $project.version$
    
    
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.angeasy.vo
  mapper-locations:
    - classpath:mybatis/mapper/Jyduty.xml

---
server:
  port: 9002
spring:
  profiles: beta9002
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://192.168.1.52:3306/prisondcdb
      username: huangcongrui
      password: azyd123
      platform: mysql
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      #minEvictableIdleTimeMillis: 30000
      #validationQuery: select 1
      #testWhileIdle: true
      #testOnBorrow: false
      #testOnReturn: false
      
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
  application:
    name: cloudServer-provider-duty   #配置eureka服务上的挂载id名，该配置需要进入配置管理流程严格控制
    
eureka:       #客户端连接注册的配置
  client:
    service-url:
    #单台注册可以多台传递，建议多台注册HA安全保证提高可靠性
      defaultZone: http://hcr:hcr12356@192.168.1.134:7001/eureka,http://hcr:hcr12356@192.168.1.134:7002/eureka
  instance:
#    lease-renewal-interval-in-seconds: 2 #设置心跳间隔时间（默认30）
#    lease-expiration-duration-in-seconds: 5 #Server应该收到心跳数据的间隔周期（默认90秒）
    instance-id: 192.168.1.134:9002        #配置显示地址信息
    prefer-ip-address: true           #以真实地址显示服务ip信息

#info信息,进入配置管理，便于维护
info:
  app.name: cloudServer
  company.name: angeasy
  build.artifactId: $project.artifactId$
  build.version: $project.version$
    
    
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.angeasy.vo
  mapper-locations:
    - classpath:mybatis/mapper/Jyduty.xml

---
server:
  port: 9003
spring:
  profiles: beta9003
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://192.168.1.52:3306/prisondcdb
      username: huangcongrui
      password: azyd123
      platform: mysql
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      #minEvictableIdleTimeMillis: 30000
      #validationQuery: select 1
      #testWhileIdle: true
      #testOnBorrow: false
      #testOnReturn: false
      
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
  application:
    name: cloudServer-provider-duty   #配置eureka服务上的挂载id名，该配置需要进入配置管理流程严格控制
    
eureka:       #客户端连接注册的配置
  client:
    service-url:
    #单台注册可以多台传递，建议多台注册HA安全保证提高可靠性
      defaultZone: http://hcr:hcr12356@192.168.1.134:7001/eureka,http://hcr:hcr12356@192.168.1.134:7002/eureka
  instance:
#    lease-renewal-interval-in-seconds: 2 #设置心跳间隔时间（默认30）
#    lease-expiration-duration-in-seconds: 5 #Server应该收到心跳数据的间隔周期（默认90秒）
    instance-id: 192.168.1.134:9003      #配置显示地址信息
    prefer-ip-address: true           #以真实地址显示服务ip信息

#info信息,进入配置管理，便于维护
info:
  app.name: cloudServer
  company.name: angeasy
  build.artifactId: $project.artifactId$
  build.version: $project.version$
    
    
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.angeasy.vo
  mapper-locations:
    - classpath:mybatis/mapper/Jyduty.xml

---
server:
  port: 9004
spring:
  profiles: beta9004
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://192.168.1.52:3306/prisondcdb
      username: huangcongrui
      password: azyd123
      platform: mysql
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      #minEvictableIdleTimeMillis: 30000
      #validationQuery: select 1
      #testWhileIdle: true
      #testOnBorrow: false
      #testOnReturn: false
      
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
  application:
    name: cloudServer-provider-duty   #配置eureka服务上的挂载id名，该配置需要进入配置管理流程严格控制
    
eureka:       #客户端连接注册的配置
  client:
    service-url:
    #单台注册可以多台传递，建议多台注册HA安全保证提高可靠性
      defaultZone: http://hcr:hcr12356@192.168.1.134:7001/eureka,http://hcr:hcr12356@192.168.1.134:7002/eureka
  instance:
#    lease-renewal-interval-in-seconds: 2 #设置心跳间隔时间（默认30）
#    lease-expiration-duration-in-seconds: 5 #Server应该收到心跳数据的间隔周期（默认90秒）
    instance-id: 192.168.1.134:9004       #配置显示地址信息
    prefer-ip-address: true           #以真实地址显示服务ip信息

#info信息,进入配置管理，便于维护
info:
  app.name: cloudServer
  company.name: angeasy
  build.artifactId: $project.artifactId$
  build.version: $project.version$
    
    
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.angeasy.vo
  mapper-locations:
    - classpath:mybatis/mapper/Jyduty.xml
 

   
  
      
      
